### ISSUE TITLE
ImportError: No module named pcapfile

### ISSUE THREAD

**Issue by spirrello** [thepacketgeek/cloud-pcap#1]
Hi,

I'm trying to deploy cloud-pcap, looks amazing by the way, but I'm getting the following error.  Can you advise on how I can get the pcapfile module installed?

python app.py shell
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from sanicap import sanitize
  File "/home/spirrello/cloud-pcap/app/sanicap.py", line 5, in <module>
    from pcapfile import savefile
ImportError: No module named pcapfile

**Comment by spirrello** [comment]
I found the problem, needed to pip install pypcapfile.
